version: '2'
services:
    cm2-postgresql:
        container_name: cm2-postgresql
        image: postgres:9.5.1
        # volumes:
        #     - ~/volumes/jhipster/CM2/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=CM2
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
